global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Library.Infrastructure.Persistence;
global using Library.Domain.Entities.Books;
global using Library.Domain.Entities.Authors;
global using System.Reflection;
