# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build API

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      working-directory: ./Library.Api 
      run: |
        dotnet publish --configuration Release --output ./publish
        cd publish
        zip -r ./publish.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: library
        path: ./Library.Api/publish/publish.zip
        if-no-files-found: error